//8
SELECT MAX(TRANSACTION_QTY) AS MAXIMUM_QUANTITY
FROM COFFEE.SHOP.SALES;

//8
SELECT MIN(TRANSACTION_QTY) AS MINIMUM_QUANTITY
FROM COFFEE.SHOP.SALES;



-----MINIMUM REVENUE 360
SELECT MAX(TRANSACTION_QTY*UNIT_PRICE) AS MAXIMUM_REVENUE
FROM COFFEE.SHOP.SALES;


----0.80
SELECT MIN(TRANSACTION_QTY*UNIT_PRICE) AS MINIMUM_REVENUE
FROM COFFEE.SHOP.SALES;



SELECT SUM(TRANSACTION_QTY*UNIT_PRICE) AS REVENUE
FROM COFFEE.SHOP.SALES;

SELECT COUNT(TRANSACTION_ID) AS NUMBER_OF_SALES,
SUM(TRANSACTION_QTY*UNIT_PRICE) AS TOTAL_REVENUE,
SUM(TRANSACTION_QTY) AS NUMBER_OF_UNITS,

TO_CHAR(TO_DATE(TRANSACTION_DATE), 'YYYYMM') AS MONTH_ID,
DAYNAME(TO_DATE(TRANSACTION_DATE)) AS DAY_OF_WEEK

FROM COFFEE.SHOP.SALES;

--------------------------------------------
SELECT
COUNT(DISTINCT TRANSACTION_ID) AS NUMBER_OF_SALES,
AVG(TRANSACTION_QTY * UNIT_PRICE) AS AVERAGE_SALES,
SUM(TRANSACTION_QTY*UNIT_PRICE) AS TOTAL_REVENUE,
SUM(TRANSACTION_QTY) AS NUMBER_OF_UNITS,
STORE_LOCATION

FROM COFFEE.SHOP.SALES
GROUP BY STORE_LOCATION;


------------------------------------------------------------------------

SELECT 

//AGGREGATED STATEMENTS
COUNT(DISTINCT TRANSACTION_ID) AS NUMBER_OF_SALES,
AVG(TRANSACTION_QTY * UNIT_PRICE) AS AVERAGE_SALES,
SUM(TRANSACTION_QTY*UNIT_PRICE) AS TOTAL_REVENUE,
SUM(TRANSACTION_QTY) AS NUMBER_OF_UNITS,


// NON-AGGREGATED STATEMENTS
TO_DATE(TRANSACTION_DATE) AS PURCHASE_DATE,
TO_CHAR(TO_DATE(TRANSACTION_DATE), 'YYYYMM') AS MONTH_ID,
DAYNAME(TO_DATE(TRANSACTION_DATE)) AS DAY_OF_WEEK, 
STORE_LOCATION,
PRODUCT_CATEGORY,
PRODUCT_DETAIL,
PRODUCT_TYPE,


//CASE STATEMENT FOR DIFFERENT TIMES 
CASE 
 
        WHEN TRANSACTION_TIME BETWEEN TIME '06:00:00' AND TIME '10:59:59' THEN 'Morning'
        WHEN TRANSACTION_TIME BETWEEN TIME '11:00:00' AND TIME '17:59:59' THEN 'Afternoon'
        WHEN TRANSACTION_TIME BETWEEN TIME '18:00:00' AND TIME '20:59:59' THEN 'Evening'
        ELSE 'Not Working hours'
        END AS TIME_BUCKET,
        
//TOTAL_REVENUE AGGREGATE STATEMENT THUS NOT IN THE GROUP BY STATEMENT
CASE

        WHEN TOTAL_REVENUE BETWEEN '0.80' AND '50' THEN 'Low spender'
        WHEN TOTAL_REVENUE BETWEEN '60' AND '120' THEN 'Mid spender'
        WHEN TOTAL_REVENUE BETWEEN '130' AND '360' THEN 'High spender'
        ELSE 'OUT OF RANGE'
        END AS SPENDER_BUCKET,


//CASE STATEMENT FOR DIFFERENT SEASONS
CASE 
 
        WHEN EXTRACT(MONTH FROM TRANSACTION_DATE) IN (12, 1, 2) THEN 'Winter'
        WHEN EXTRACT(MONTH FROM TRANSACTION_DATE) IN (3, 4, 5) THEN 'Spring'
        WHEN EXTRACT(MONTH FROM TRANSACTION_DATE) IN (6, 7, 8) THEN 'Summer'
        WHEN EXTRACT(MONTH FROM TRANSACTION_DATE) IN (9, 10, 11) THEN 'Fall'
        ELSE 'Unknown'
    END AS SEASON,
    
//CASE STAEMENT FOR TRANSACTION_QTY

CASE 
    WHEN TRANSACTION_QTY BETWEEN '1' AND '2' THEN 'Low'
    WHEN TRANSACTION_QTY BETWEEN '3' AND '5' THEN 'Mid'
    WHEN TRANSACTION_QTY BETWEEN '6' AND '8' THEN 'High'
    ELSE 'INVALID'
END AS QUANTITY_BUCKET

FROM COFFEE.SHOP.SALES




//GROUP BY ALL NON-AGGREGATED STATEMENTS
GROUP BY PURCHASE_DATE,
MONTH_ID,
DAY_OF_WEEK,
STORE_LOCATION,
PRODUCT_CATEGORY,
PRODUCT_DETAIL,
PRODUCT_TYPE,
TIME_BUCKET,
SEASON,
QUANTITY_BUCKET





